fix: Only check for git-lfs if .gitattributes contains "lfs"

diff --git a/git/hooks/post-checkout b/git/hooks/post-checkout
--- a/git/hooks/post-checkout
+++ b/git/hooks/post-checkout
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 
-command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
-git lfs post-checkout "$@"
+if [[ -e ".gitattributes" ]] && grep -q "lfs" ".gitattributes"; then
+	command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-checkout.\n"; exit 2; }
+	git lfs post-checkout "$@"
+fi
 
 if [[ "${1}" == "0000000000000000000000000000000000000000" ]]; then
 	# This must be a new repo being cloned
